# Generated by Django 6.0.4 on 2026-04-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional middle name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Student Profile Picture', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Information Technology', 'Information Technology'), ('Business Administration', 'Business Administration'), ('Arts and Humanities', 'Arts and Humanities'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year / Freshman'), (2, 'Second Year / Sophomore'), (3, 'Third Year / Junior'), (4, 'Fourth Year / Senior')], null=True),
        ),
    ]
