# Generated by Django 6.0.4 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_alter_customuser_department'),
        ('exams', '0004_alter_exam_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='Current semester for students', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher is responsible for (Teachers only).', to='exams.course'),
        ),
    ]
