# Generated by Django 6.0.4 on 2026-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_semester_customuser_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the student', null=True),
        ),
    ]
