# Generated by Django 6.0.4 on 2026-04-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_instructions_exam_negative_marking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Information Technology', 'Information Technology'), ('Business Administration', 'Business Administration'), ('Arts and Humanities', 'Arts and Humanities'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics')], help_text='If set, only students in this department can see and take the exam.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='section_name',
            field=models.CharField(default='General', help_text='Section of the exam (e.g. General, Aptitude, Technical)', max_length=100),
        ),
    ]
