# Generated by Django 6.0.4 on 2026-04-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_alter_customuser_department'),
        ('exams', '0003_exam_department_question_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(blank=True, help_text='If set, only students in this department can see and take the exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
