# Generated by Django 6.0.4 on 2026-04-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_semester_customuser_subjects'),
        ('exams', '0004_alter_exam_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(blank=True, help_text='Semester number (1-8)', null=True),
        ),
    ]
