# Generated by Django 6.0.4 on 2026-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_course_department_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='negative_marking',
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marks',
            field=models.FloatField(default=0.0, help_text='Amount to deduct per wrong answer (e.g. 0.25)'),
        ),
    ]
