# Generated by Django 6.0.4 on 2026-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exam_negative_marking_exam_negative_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_reattempt',
            field=models.BooleanField(default=True, help_text='If enabled, students can re-attempt exactly once if they fail.'),
        ),
    ]
