# Generated by Django 6.0.4 on 2026-04-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_allow_reattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='random_question_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of questions to randomly select from the bank for each attempt. Set to 0 to use all questions.'),
        ),
    ]
