# Generated by Django 6.0.4 on 2026-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='reattempt_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for re-attempting this exam (0 for free).', max_digits=10),
        ),
    ]
