# Generated by Django 6.0.4 on 2026-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_reattempt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='reattempt_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Fee for re-attempting this exam (0 for free).', max_digits=10),
        ),
    ]
