# Generated by Django 6.0.4 on 2026-05-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_exam_reattempt_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='reattempt_price',
        ),
    ]
